version: '3.9'

services:
  app:
    image: node:latest
    restart: unless-stopped
    entrypoint: yarn run dev:watch
    ports:
      - 20884:8080
    volumes:
      - ./:/app
    working_dir: /app
    user: '33'
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: budget
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
#    ports:
#      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:

networks:
  default:
    name: budget-api
