version: '3'

services:
  app:
    image: node:latest
    restart: unless-stopped
    entrypoint: yarn run dev:watch
    ports:
      - 8089:8080
    volumes:
      - /var/www/#dev/root/budget-rest-api/:/app
    networks:
      - budget-rest-api
    working_dir: /app
    user: '33'
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    networks:
      - budget-rest-api
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:

networks:
  budget-rest-api:
